'use client';

import { useState } from 'react';
import {
    Upload,
    Sparkles,
    Target,
    Mic,
    BookOpen,
    ChevronDown,
    ChevronUp,
    PlayCircle,
    CheckCircle2,
    ArrowRight,
    HelpCircle,
} from 'lucide-react';
import GradientHeader from '@/components/common/GradientHeader';

interface Step {
    icon: typeof Upload;
    title: string;
    description: string;
    tips?: string[];
}

interface FaqItem {
    question: string;
    answer: string;
}

// ── Edit these to match your actual features/flow ──────────────────
const STEPS: Step[] = [
    {
        icon: Upload,
        title: '1. Upload Your Resume',
        description:
            'Go to the Resume page and upload your CV/resume (PDF or DOCX format). Our system will automatically extract your skills, experience, and education.',
        tips: [
            'For best results, use a clean, up-to-date resume',
            'PDF format gives more reliable results',
        ],
    },
    {
        icon: Target,
        title: '2. Select Your Target Role',
        description:
            'Enter the job role you want to apply for (e.g. "Frontend Developer" or "Data Analyst"). The system will compare your skills against that role\'s requirements.',
        tips: [
            'The more specific the role, the more accurate the results',
            'Both matched and missing skills will be shown',
        ],
    },
    {
        icon: Sparkles,
        title: '3. Review Your Skill Gap Analysis',
        description:
            'See which skills you already have (matched) and which ones you still need to learn (missing) for your target role.',
    },
    {
        icon: Mic,
        title: '4. Practice Interview Prep',
        description:
            'Head to the Interview Prep tab to practice AI-generated interview questions for your target role — progressing from Easy to Hard.',
        tips: [
            'Write an answer for each question and hit "Submit for Review"',
            'The AI will give you a score and improvement tips',
        ],
    },
    {
        icon: BookOpen,
        title: '5. Follow Your Roadmap',
        description:
            'Get a personalized learning roadmap to cover your missing skills — a step-by-step guide to help you become qualified for your target role.',
    },
];

const FAQS: FaqItem[] = [
    {
        question: 'Where is my resume stored?',
        answer:
            'Your resume is only analyzed for this session. We don\'t permanently store your resume file — only the extracted info (skills, role) stays temporarily in your browser session.',
    },
    {
        question: 'How are the interview questions generated?',
        answer:
            'Questions are generated by AI, based on your actual resume skills and your target role — so they stay relevant and personalized instead of generic.',
    },
    {
        question: 'Can I practice for multiple roles?',
        answer:
            'Yes, you can enter a new role in the target role field and re-run the analysis and generate new interview questions.',
    },
    {
        question: "What if my resume isn't being read properly?",
        answer:
            'Make sure the file is in PDF or DOCX format and is text-based (not a scanned image). You can also add your skills manually if the issue persists.',
    },
];

export default function HowToUsePage() {
    const [openFaq, setOpenFaq] = useState<number | null>(null);

    return (
        <main className="min-h-screen bg-[var(--bg)]">
            <div className="max-w-3xl mx-auto">
                <GradientHeader
                    eyebrow="Guide"
                    title="How to Use This Website"
                    subtitle="A step-by-step guide to help you get the most out of this platform."
                    showBack
                />

                <div className="px-5 mt-6 space-y-8 pb-12">
                    {/* ── Quick overview banner ─────────────────────────────── */}
                    <div className="bg-[var(--surface)] rounded-2xl border border-[var(--border)] p-6 flex items-start gap-4">
                        <div className="w-11 h-11 rounded-xl bg-[var(--accent)]/10 flex items-center justify-center flex-shrink-0">
                            <PlayCircle size={20} className="text-[var(--accent)]" />
                        </div>
                        <div>
                            <h2 className="font-display text-base font-semibold mb-1">Getting Started</h2>
                            <p className="text-sm text-[var(--text-muted)] leading-relaxed">
                                In just 5 steps, you can complete your career analysis, skill gap review, and interview practice.
                                Details for each step are below.
                            </p>
                        </div>
                    </div>

                    {/* ── Step by Step Guide ─────────────────────────────────── */}
                    <section>
                        <h3 className="font-display text-lg font-bold mb-4 flex items-center gap-2">
                            <CheckCircle2 size={18} className="text-[var(--accent)]" />
                            Step-by-Step Guide
                        </h3>
                        <div className="space-y-3">
                            {STEPS.map((step, i) => {
                                const Icon = step.icon;
                                return (
                                    <div
                                        key={i}
                                        className="bg-[var(--surface)] rounded-2xl border border-[var(--border)] p-5 flex gap-4"
                                    >
                                        <div className="w-10 h-10 rounded-xl bg-[var(--accent)]/10 flex items-center justify-center flex-shrink-0">
                                            <Icon size={18} className="text-[var(--accent)]" />
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <h4 className="font-semibold text-sm text-[var(--text)] mb-1">{step.title}</h4>
                                            <p className="text-xs text-[var(--text-muted)] leading-relaxed">{step.description}</p>
                                            {step.tips && step.tips.length > 0 && (
                                                <ul className="mt-2 space-y-1">
                                                    {step.tips.map((tip, j) => (
                                                        <li
                                                            key={j}
                                                            className="text-[11px] text-[var(--accent)] flex items-start gap-1.5"
                                                        >
                                                            <span className="mt-0.5">💡</span> {tip}
                                                        </li>
                                                    ))}
                                                </ul>
                                            )}
                                        </div>
                                        {i < STEPS.length - 1 && (
                                            <ArrowRight
                                                size={14}
                                                className="text-[var(--text-muted)] flex-shrink-0 hidden md:block self-center opacity-40"
                                            />
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </section>

                    {/* ── FAQ Section ─────────────────────────────────────────── */}
                    <section>
                        <h3 className="font-display text-lg font-bold mb-4 flex items-center gap-2">
                            <HelpCircle size={18} className="text-[var(--accent)]" />
                            Frequently Asked Questions
                        </h3>
                        <div className="space-y-2">
                            {FAQS.map((faq, i) => {
                                const isOpen = openFaq === i;
                                return (
                                    <div
                                        key={i}
                                        className="bg-[var(--surface)] rounded-xl border border-[var(--border)] overflow-hidden"
                                    >
                                        <button
                                            onClick={() => setOpenFaq(isOpen ? null : i)}
                                            className="w-full flex items-center justify-between p-4 text-left"
                                        >
                                            <span className="text-sm font-medium text-[var(--text)]">{faq.question}</span>
                                            {isOpen ? (
                                                <ChevronUp size={16} className="text-[var(--text-muted)] flex-shrink-0 ml-2" />
                                            ) : (
                                                <ChevronDown size={16} className="text-[var(--text-muted)] flex-shrink-0 ml-2" />
                                            )}
                                        </button>
                                        {isOpen && (
                                            <div className="px-4 pb-4 border-t border-[var(--border)] pt-3">
                                                <p className="text-xs text-[var(--text-muted)] leading-relaxed">{faq.answer}</p>
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </section>
                </div>
            </div>
        </main>
    );
}